var beads_10_each = [

    "stim_beads_each/bin_1_0.jpeg",
    "stim_beads_each/bin_1_1.jpeg",
    "stim_beads_each/bin_1_2.jpeg",
    "stim_beads_each/bin_1_3.jpeg",
    "stim_beads_each/bin_1_4.jpeg",
    "stim_beads_each/bin_1_5.jpeg",
    "stim_beads_each/bin_1_6.jpeg",
    "stim_beads_each/bin_1_7.jpeg",
    "stim_beads_each/bin_1_8.jpeg",
    "stim_beads_each/bin_1_9.jpeg",
    "stim_beads_each/bin_1_10.jpeg",
    "stim_beads_each/bin_2_0.jpeg",
    "stim_beads_each/bin_2_1.jpeg",
    "stim_beads_each/bin_2_2.jpeg",
    "stim_beads_each/bin_2_3.jpeg",
    "stim_beads_each/bin_2_4.jpeg",
    "stim_beads_each/bin_2_5.jpeg",
    "stim_beads_each/bin_2_6.jpeg",
    "stim_beads_each/bin_2_7.jpeg",
    "stim_beads_each/bin_2_8.jpeg",
    "stim_beads_each/bin_2_9.jpeg",
    "stim_beads_each/bin_2_10.jpeg",
    "stim_beads_each/bin_3_0.jpeg",
    "stim_beads_each/bin_3_1.jpeg",
    "stim_beads_each/bin_3_2.jpeg",
    "stim_beads_each/bin_3_3.jpeg",
    "stim_beads_each/bin_3_4.jpeg",
    "stim_beads_each/bin_3_5.jpeg",
    "stim_beads_each/bin_3_6.jpeg",
    "stim_beads_each/bin_3_7.jpeg",
    "stim_beads_each/bin_3_8.jpeg",
    "stim_beads_each/bin_3_9.jpeg",
    "stim_beads_each/bin_3_10.jpeg",


]